CREATE TABLE IF NOT EXISTS postgres.addresses
(
    id integer PRIMARY KEY  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    home character varying(255) COLLATE pg_catalog."default",
    post_index integer,
    street character varying(255) COLLATE pg_catalog."default"
)

    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS postgres.users
(
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    birthday timestamp,
    name character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    address_id integer references addresses(id)
)

TABLESPACE pg_default;
